AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
  Distrubutes SSO PermissionSet role arn to all regions in SSM parameter store

Parameters:
  ParameterStorePrefix:
    Type: String
    Description: Prefix for the parameters in parameter store
  S3Bucket:
    Type: String
    Description: Name of S3 bucket containing packaged code
  S3BucketKey:
    Type: String
    Description: Packaged code

Resources:
  TriggerMonthly:
    Type: AWS::Events::Rule
    Properties:
      Description: Triggers on the creation of an SSO PermissionSet role
      ScheduleExpression: cron(0 0 1 * ? *)
      Targets:
        - Arn: !GetAtt DistributeSSORoles.Arn
          Id: DistributeSSORoles
  TriggerOnEvent:
    Type: AWS::Events::Rule
    Properties:
      Description: Triggers on the creation of an SSO PermissionSet role
      EventPattern: |
        {
          "source": [
            "aws.iam"
          ],
          "detail-type": [
            "AWS API Call via CloudTrail"
          ],
          "detail": {
            "eventSource": [
              "iam.amazonaws.com"
            ],
            "userAgent": [
                "sso.amazonaws.com"
              ],
            "eventName": [
              "CreateRole",
              "DeleteRole"
            ]
          }
        }
      Targets:
        - Arn: !GetAtt DistributeSSORoles.Arn
          Id: DistributeSSORoles


  TriggerLambda:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt DistributeSSORoles.Arn
      Principal: events.amazonaws.com


  DistributeSSORolesLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub
        - /aws/lambda/${LambdaName}
        - { LambdaName: !Ref DistributeSSORoles }
      RetentionInDays: 90

  DistributeSSORoles:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      CodeUri:
        Bucket: !Ref S3Bucket
        Key: !Ref S3BucketKey
      Description: This lambda will put SSO Permission set role arns into SSM Parameter stor in all available regions
      Handler: not.used.in.provided.runtime
      MemorySize: 512
      Runtime: provided
      Timeout: 900
      Environment:
        Variables:
          ParameterStorePrefix: !Ref ParameterStorePrefix
          DISABLE_SIGNAL_HANDLERS: true
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - ssm:PutParameter
              - ssm:DeleteParameter
            Resource: !Sub arn:aws:ssm:*:${AWS::AccountId}:parameter/ParameterStorePrefix/*
          - Effect: Allow
            Action:
              - ssm:GetParametersByPath
            Resource: !Sub arn:aws:ssm:*:${AWS::AccountId}:parameter/aws/service/global-infrastructure/regions